# Generated by Django 5.1.6 on 2025-02-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='fecha',
        ),
        migrations.AddField(
            model_name='candidato',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='voto',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votaciones.estudiante'),
        ),
    ]
