# Generated by Django 5.1.6 on 2025-02-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_remove_voto_fecha_candidato_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='imagen',
            field=models.ImageField(default='candidatos/perfil.png', upload_to='candidatos/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votaciones.candidato'),
        ),
        migrations.AddField(
            model_name='voto',
            name='grado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votaciones.grado'),
        ),
    ]
