# Generated by Django 5.1.6 on 2025-02-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0003_candidato_imagen_estudiante_candidato_voto_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
