# Generated by Django 5.1.6 on 2025-02-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0004_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votaciones.mesa'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='nombre',
            field=models.IntegerField(unique=True),
        ),
    ]
