# Generated by Django 5.1.6 on 2025-02-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0005_estudiante_mesa_alter_mesa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votaciones.mesa'),
        ),
    ]
