# Generated by Django 5.1.6 on 2025-03-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0006_voto_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='tarjeton',
            field=models.CharField(default='N/A', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mesa',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
