# Generated by Django 5.1.6 on 2025-03-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0007_candidato_tarjeton_alter_mesa_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='imagen',
            field=models.ImageField(upload_to='candidatos/'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tarjeton',
            field=models.IntegerField(unique=True),
        ),
    ]
