# Generated by Django 5.1.6 on 2025-03-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0008_remove_candidato_descripcion_alter_candidato_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='tarjeton',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
