# Generated by Django 5.1.6 on 2026-02-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0009_alter_candidato_tarjeton'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tarjeton',
            field=models.IntegerField(unique=True),
        ),
    ]
