# Generated by Django 5.1.6 on 2026-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0010_candidato_descripcion_alter_candidato_tarjeton'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['numero']},
        ),
        migrations.AddField(
            model_name='grado',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
