# Generated by Django 5.1.6 on 2026-02-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0011_alter_grado_options_grado_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='numero',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
